### ISSUE TITLE
from my_pip_package import __version__ fails if that package has modules from dependencies

### ISSUE THREAD

**Issue by Nixellion** [MichaelKim0407/tutorial-pip-package#2]
`from my_pip_package import __version__` command may fail and package may not be installed if the file containing version imports something from uninstalled packages, before requirements are installed which leads to an error.

**Comment by MichaelKim0407** [comment]
My recommendation is either
1. Don't put code in `__init__.py`
2. Wrap your code in `try: ... except ImportError: pass`
